### ISSUE TITLE
Forum is very slow

### ISSUE THREAD

**Issue by danielb987** [My-Little-Forum/mylittleforum#673] opened 2023-03-19 16:28 UTC
Thank you for your work on MyLittleForum!

We have a MyLittleForum with version 20220803.1 at https://www.jvmv2.se/forum/index.php

The forum is very slow so I did a couple of things to identify why:

I added this code in the beginning of `index.php`:
```
// Daniel
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
$start_time = hrtime(true);
// Daniel
```

I added this code at the end of `index.php`:
```
echo "<p><hr><p>\n";

function cmp($a, $b)
{
    if ($a->time == $b->time) {
        return 0;
    }
    return ($a->time < $b->time) ? -1 : 1;
}

usort($queries, "cmp");

foreach ($queries as $query) {
	$t = round($query->time/1000/1000,0);
	if ($t >= 10) {
		echo "Time: ".$t."<br>".$query->query."<hr>\n";
	}
}

$time = hrtime(true) - $start_time;
echo "<p>Total time: ".round($time/1000/1000,0)."<p>\n";
```

I added this code to the end of `config/db_settings.php`:
```
$queries = array();

class DanielQuery {
	public $query;
	public $time;
}

function daniel_mysqli_query(mysqli $mysql, string $query, int $result_mode = MYSQLI_STORE_RESULT) {
	global $queries;

//	echo $query."<br>\n";
	$start_time = hrtime(true);
	$result = mysqli_query($mysql, $query, $result_mode);
	$time = hrtime(true) - $start_time;

	$theQuery = new DanielQuery();
	$theQuery->query = $query;
	$theQuery->time = $time;
	$queries[] = $theQuery;

	return $result;
}
```

And I did a search and replace of all occurrences of `@mysqli_query` to `daniel_mysqli_query`.

The result is this. The time is shown in the number of milliseconds and only queries that take 10 seconds or more are shown.

```
Time: 100
SELECT id, tid FROM mlf2_entries LEFT JOIN mlf2_akismet_rating ON mlf2_akismet_rating.eid = mlf2_entries.id LEFT JOIN mlf2_b8_rating ON mlf2_b8_rating.eid = mlf2_entries.id WHERE ((pid = 0 AND category IN (0, 4, 5, 6, 7, 8, 9, 25, 14, 23, 19, 22, 24, 10, 21, 11, 12, 13, 15, 16, 26, 18, 20, 27)) OR (pid = 0 AND sticky = 2)) AND (mlf2_akismet_rating.spam = 0 AND mlf2_b8_rating.spam = 0) ORDER BY sticky DESC, time DESC LIMIT 0, 30

Time: 222
SELECT COUNT(*) FROM mlf2_entries LEFT JOIN mlf2_akismet_rating ON mlf2_akismet_rating.eid = mlf2_entries.id LEFT JOIN mlf2_b8_rating ON mlf2_b8_rating.eid = mlf2_entries.id WHERE pid = 0 AND (mlf2_akismet_rating.spam = 0 AND mlf2_b8_rating.spam = 0) AND category IN (0, 4, 5, 6, 7, 8, 9, 25, 14, 23, 19, 22, 24, 10, 21, 11, 12, 13, 15, 16, 26, 18, 20, 27)

Time: 788
SELECT COUNT(*) FROM mlf2_entries LEFT JOIN mlf2_akismet_rating ON mlf2_akismet_rating.eid = mlf2_entries.id LEFT JOIN mlf2_b8_rating ON mlf2_b8_rating.eid = mlf2_entries.id WHERE (mlf2_akismet_rating.spam = 1 OR mlf2_b8_rating.spam = 1)

Time: 966
SELECT COUNT(*) FROM mlf2_entries LEFT JOIN mlf2_akismet_rating ON mlf2_akismet_rating.eid = mlf2_entries.id LEFT JOIN mlf2_b8_rating ON mlf2_b8_rating.eid = mlf2_entries.id WHERE category IN (0, 4, 5, 6, 7, 8, 9, 25, 14, 23, 19, 22, 24, 10, 21, 11, 12, 13, 15, 16, 26, 18, 20, 27) AND (mlf2_akismet_rating.spam = 0 AND mlf2_b8_rating.spam = 0)

Time: 3356
SELECT id, pid, tid, name, user_name, ft.user_id, UNIX_TIMESTAMP(ft.time) AS time, UNIX_TIMESTAMP(ft.time + INTERVAL 0 MINUTE) AS timestamp, UNIX_TIMESTAMP(last_reply) AS last_reply, subject, category, rst.user_id AS req_user FROM mlf2_entries AS ft LEFT JOIN mlf2_userdata ON mlf2_userdata.user_id = ft.user_id LEFT JOIN mlf2_read_entries AS rst ON rst.posting_id = ft.id AND rst.user_id = 0 LEFT JOIN mlf2_akismet_rating ON mlf2_akismet_rating.`eid` = `ft`.`id` LEFT JOIN mlf2_b8_rating ON mlf2_b8_rating.`eid` = `ft`.`id` WHERE (mlf2_akismet_rating.spam = 0 AND mlf2_b8_rating.spam = 0) AND category IN (0, 4, 5, 6, 7, 8, 9, 25, 14, 23, 19, 22, 24, 10, 21, 11, 12, 13, 15, 16, 26, 18, 20, 27) ORDER BY ft.time DESC LIMIT 40

Total time: 5484
```

You can with the result on this forum:  https://www.jvmv2.se/daniel/forum/
The result is on the bottom of the page.

The conclusion is that several queries take 100 milliseconds or more. And that one query takes several seconds. The solution is probably to add one or more indexes to one or more tables.

**Comment by auge8472** [comment] 2023-03-19 18:55
Thank you for your investigation. I'll take a look at it.

**Comment by loesler** [comment] 2023-03-20 09:20
> The solution is probably to add one or more indexes to one or more tables.

That is true. However, if you check the table definitions, almost all (relevant) columns are already indexed.

**Comment by danielb987** [comment] 2023-03-21 13:41
@auge8472 
Thank you for your investigation!
It seems that there is not much to do about it.

**Comment by auge8472** [comment] 2023-03-21 15:15
> It seems that there is not much to do about it.

We'll see. In other software products you do not see such blatant performance issues so we have to search for better solutions than we have now.

**Comment by auge8472** [comment] 2023-04-03 21:14
I checked the longest lasting query in phpMyAdmin (not the most convinient tool for this purpose) with `EXPLAIN` putting `EXPLAIN FORMAT=JSON` before the keyword `SELECT` and `STRAIGHT_JOIN` behind it. I have only my testing and development forums, the largest with only 87 entries, so the performance in itself is satisfying.

~~~ sql
EXPLAIN FORMAT=JSON SELECT STRAIGHT_JOIN id, pid, tid …
~~~

I had to change the category selection and to adapt the table names to mine but apart from these modifications the query remained the same. Even with a satisfying performance I found a serious issue.

With only three category IDs (two exists in my forum, the third is not existing here) the explain was inconspicuous. The query selected 17 out of the 87 rows from `mlf2_entries`, joined 17 rows `from mlf_userdata`, `mlf2_read_entries`, `mlf2_b8_rating` and `mlf2_akismet_rating`. Per scan (selected main row) only one row of the joined tables got "examined". That's what I would expect. The indexes worked, the query found the matching entries from the other tables with the existing indexes.

~~~
        {
          "table": {
            "table_name": "mlf24_akismet_rating",
            "access_type": "eq_ref",
            "possible_keys": [
              "PRIMARY"
            ],
            "key": "PRIMARY",
            "used_key_parts": [
              "eid"
            ],
            "key_length": "4",
            "ref": [
              "db53644.ft.id"
            ],
            "rows_examined_per_scan": 1,
            "rows_produced_per_join": 1,
            "filtered": "10.00",
            "cost_info": {
              "read_cost": "17.00",
              "eval_cost": "0.17",
              "prefix_cost": "69.80",
              "data_read_per_join": "13"
            },
            "used_columns": [
              "eid",
              "spam"
            ],
            "attached_condition": "(`db53644`.`mlf24_akismet_rating`.`spam` = 0)"
          }
        }
~~~

Changing the category selection to all categories of my forum by adding all IDs to the `IN()` group changed the situation completely. Now the query selected 86 out of 87 rows from `mlf2_entries` (there is one row without a category), joined 86 rows `from mlf_userdata`, `mlf2_read_entries`, `mlf2_b8_rating` with only one examined row per scan. But now the query was not able to use the index `e_id` in the table `mlf2_akismet_rating`. Because of that the query performed a long lasting full table scan instead.

~~~
        {
          "table": {
            "table_name": "mlf24_akismet_rating",
            "access_type": "ALL",
            "possible_keys": [
              "PRIMARY"
            ],
            "rows_examined_per_scan": 86,
            "rows_produced_per_join": 85,
            "filtered": "1.16",
            "using_join_buffer": "hash join",
            "cost_info": {
              "read_cost": "16.20",
              "eval_cost": "8.60",
              "prefix_cost": "293.06",
              "data_read_per_join": "687"
            },
            "used_columns": [
              "eid",
              "spam"
            ],
            "attached_condition": "((`db_name`.`mlf24_akismet_rating`.`eid` = `db_name`.`ft`.`id`) and (`db_name`.`mlf24_akismet_rating`.`spam` = 0))"
          }
        }
~~~

For comparision the corresponding block for the join with table `mlf24_b8_rating` in the query with the 86 resulting lines.

~~~
        {
          "table": {
            "table_name": "mlf24_b8_rating",
            "access_type": "eq_ref",
            "possible_keys": [
              "PRIMARY",
              "B8_spam"
            ],
            "key": "PRIMARY",
            "used_key_parts": [
              "eid"
            ],
            "key_length": "4",
            "ref": [
              "db53644.ft.id"
            ],
            "rows_examined_per_scan": 1,
            "rows_produced_per_join": 85,
            "filtered": "100.00",
            "cost_info": {
              "read_cost": "1.00",
              "eval_cost": "8.60",
              "prefix_cost": "302.66",
              "data_read_per_join": "687"
            },
            "used_columns": [
              "eid",
              "spam"
            ],
            "attached_condition": "(`db53644`.`mlf24_b8_rating`.`spam` = 0)"
          }
        }
~~~

The big differences are `"rows_examined_per_scan": 1` in the table `mlf24_b8_rating` versus `"rows_examined_per_scan": 86` in the table `mlf24_akismet_rating` and (presumably a result of this difference) the read cost of `1.00` for the table `mlf24_b8_rating` versus `16.20` for the table `mlf24_akismet_rating`. Additionally there is a difference between the first run with `WHERE categories IN(1, 2, 3)` (category 2 does not exist) versus the second run with all categories in the `IN`-clause. In the first case we can see `"attached_condition": "(db_name.mlf24_akismet_rating.spam = 0)"`, in the second and slow case we see `"attached_condition": "((db_name.mlf24_akismet_rating.eid = db_name.ft.id) and (db_name.mlf24_akismet_rating.spam = 0))"` (removed the backticks around the table and column names for readability).

Further observations [can be read in the project forum](https://mylittleforum.net/forum/index.php?id=15479).

Can anyone confirm what I have observed? Or does someone sees a completely different outcome?

**Comment by loesler** [comment] 2023-04-04 19:46
Hi,

no, I cannot confirm this behavior. Did you check the keys of both tables? If I interchange the JOIN statements b8 <--> akismet, the result changes. 

What is happend, if we restrict the JOIN statements instead of using WHERE, i.e.,

```
SELECT id, pid, tid, name, user_name, ft.user_id, UNIX_TIMESTAMP(ft.time) AS time, UNIX_TIMESTAMP(ft.time + INTERVAL 0 MINUTE) AS timestamp, 
UNIX_TIMESTAMP(last_reply) AS last_reply, subject, category, rst.user_id AS req_user FROM mlf2_entries AS ft 

LEFT JOIN mlf2_userdata            ON mlf2_userdata.user_id = ft.user_id 
LEFT JOIN mlf2_read_entries AS rst ON rst.posting_id = ft.id AND rst.user_id = 0 

LEFT JOIN mlf2_b8_rating           ON mlf2_b8_rating.`eid` = `ft`.`id`      AND mlf2_b8_rating.spam = 0
LEFT JOIN mlf2_akismet_rating      ON mlf2_akismet_rating.`eid` = `ft`.`id` AND mlf2_akismet_rating.spam = 0

WHERE category IN
(0, 4, 5, 6, 7, 8, 9, 25, 14, 23, 19, 22, 24, 10, 21, 11, 12, 13, 15, 16, 26, 18, 20, 27) ORDER BY ft.time 
```

Is there a noticeable effect?

/MIcha

**Comment by auge8472** [comment] 2024-04-26 09:15
Long time ago ...

> no, I cannot confirm this behavior. Did you check the keys of both tables? If I interchange the JOIN statements b8 <--> akismet, the result changes.

Due to the tests of the reorganised upgrade script, we became aware of missing indexes for the table `mlf2_akismet_rating` in case of an *upgrade*. The indexes exists in a forum, that was *installed* with the current stable release. I expect the missing indexes to be the cause of *this* observation I made.

**Comment by auge8472** [comment] 2024-04-26 09:27
)The reorganisation of the upgrade process[^1] and the corrections to it[^2], which were made possible to a large extent by @joeiacoponi1's tests[^3] - I might not have noticed some things - and @joeiacoponi1's work on improving SQL performance[^4] should at least partially eliminate the cause of this report.

The corretions have not yet been added. I am therefore leaving the issue open, but I would like to state that we are close to a solution.

[^1]: in #680
[^2]: in #707
[^3]: in [the project forum](https://mylittleforum.net/forum/index.php?id=17657) and in #708 and #709
[^4]: in #713

**Comment by auge8472** [comment] 2024-08-04 15:39
@danielb987 Even you have decided to move to phpBB with your forum after we wasn't able to solve the issue within a reasonable time, I would like to ask you to upload the new release to the archived MLF instance. It contains noticeable performance improvements. I am curious whether the changes will solve your performance problem of if it is related to another section of the several queries.

There was several changes regarding the way to join the spam-prevention related tables. All of the queries you have listed in your report are joining these tables. So it looks as there could be improvements. And should it only be for those who want to look into the archive, it cound be worth the work.

**Comment by auge8472** [comment] 2024-11-19 22:00
I'm closing here because I no longer expect a response.

**Closed by auge8472** 2024-11-19 22:00 UTC
